# fly.toml app configuration file generated for blossom-cold-cloud-8187 on 2026-04-14T17:18:52-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'blossom-cold-cloud-8187'
primary_region = 'iad'

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8080"
  PROXY_PREFIX = "/cdn/m/"
  EPOXY_PREFIX = "/cdn/n/"
  BAREMUX_PREFIX = "/cdn/w/"
  WISP_PATH = "/sock/"
  SCRAMJET_PREFIX = "/~/"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
